name: TryHackMe Badge

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        # This assumes puppeteer is listed in your package.json dependencies

      - name: Capture Screenshot
        run: node capture-screenshot.js
        # Ensure this script captures the screenshot with transparency and cropping.

      # Optional step to commit the screenshot back to the repository
      - name: Commit screenshot
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f badge.png
          git commit -m "Add generated badge screenshot" -a || echo "No changes to commit"
          git push
